name: Build Windows Tools image

on:
  schedule:
    - cron: '30 0 15 * *'
  workflow_dispatch:

jobs: 
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Pull base image
        run: docker pull cirrusci/android-sdk:30-windowsservercore-2019

      - name: Build image
        run: docker build --tag ky1vstar/flutter-tools:wsc2019-vs2019 windows\tools

      - name: Push image
        run: docker push ky1vstar/flutter-tools:wsc2019-vs2019
