name: Build Windows Containers

on:
  push:

jobs:
  stable:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Pull base image
        run: docker pull cirrusci/windowsservercore:visualstudio2019
