name: Build Windows Flutter image

on:
  # schedule:
  #   - cron: '30 */2 * * *'
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Flutter version'     
        required: true
        type: string
      flutter_channel:
        description: 'Flutter channel'     
        required: true
        type: choice
        options:
          - stable
          - beta
      update_channel_image:
        description: 'Update channel image'     
        required: true
        default: false
        type: boolean

jobs:
  define_configs:
    runs-on: ubuntu-latest
    outputs:
      configs: ${{ steps.configs.outputs.configs }}
    steps:
      - name: Define configs
        id: configs
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]] ;then
            echo 'configs=[{"flutter_version": "${{ inputs.flutter_version }}", "flutter_channel": "${{ inputs.flutter_channel }}", "update_channel_image": ${{ inputs.update_channel_image }}}]' >> "$GITHUB_OUTPUT"
          else
            echo 'configs=[{"flutter_channel": "stable"}, {"flutter_channel": "beta"}]' >> "$GITHUB_OUTPUT"
          fi


  build:
    needs: define_configs
    strategy:
      matrix:
        config: ${{ fromJSON(needs.define_configs.outputs.configs) }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/windows-reusable.yml
    with:
      flutter_version: ${{ matrix.config.flutter_version }}
      flutter_channel: ${{ matrix.config.flutter_channel }}
      update_channel_image: ${{ matrix.config.update_channel_image }}
    secrets: inherit
