name: Build Windows Containers

on:
  push:

jobs:
  stable:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Pull base image
        run: docker pull cirrusci/windowsservercore:visualstudio2019
