name: Build Windows Tools image

on:
  schedule:
    - cron: '30 0 15 * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        config:
          - server_version: 2019
            vs_buildtools_version: 16
            image_tag: flutter-tools:wsc2019-vs2019
          - server_version: 2019
            vs_buildtools_version: 17
            image_tag: flutter-tools:wsc2019
          - server_version: 2022
            vs_buildtools_version: 17
            image_tag: flutter-tools:wsc2022
    runs-on: windows-${{ matrix.config.server_version }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # https://stackoverflow.com/questions/56992563/vs-buildtools-wont-install-in-docker-container-on-windows-server-2016
      - name: Fix Docker container storage size
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "storage-opts": [
                "size=100GB"
              ]
            }

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build images
        run: >
          docker build 
          --pull
          --build-arg server_version=${{ matrix.config.server_version }}
          --build-arg vs_buildtools_version=${{ matrix.config.vs_buildtools_version }}
          --tag ky1vstar/${{ matrix.config.image_tag }}
          --tag ghcr.io/${{ github.repository_owner }}/${{ matrix.config.image_tag }}
          windows\tools

      - name: Push images
        run: |
          docker push ky1vstar/${{ matrix.config.image_tag }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.config.image_tag }}
